#!/bin/bash

unset GIT_DIR

export BOB_DIR="$PWD/bob"
export BOB_NAME="$(basename $PWD | sed 's/.git$//')"
export BOB_RELEASE="$PWD/bob/release"
export BOB_RELEASE_TARBALL="$PWD/bob/release.tar.gz"

cd bob

silent () {
	$@ > /dev/null 2>&1
}

error () {
	echo $@ >&2
	exit 1
}

if [ -d checkout ]; then
	cd checkout
	silent git reset --hard
	silent git pull ../.. master --force
else
	silent git clone .. checkout
	cd checkout
fi

[ -f ../scripts/profile ] && . ../scripts/profile || error Profile failed. Aborting...
[ -f ../scripts/build ] && ../scripts/build || error Build failed. Aborting...

cd ../checkout
rsync -ar --delete-after --exclude '/.git' . ../release
cd ..
cp scripts/bundled-launch release/bundled-launch
chmod +x release/bundled-launch
cd release
tar cz . > $BOB_RELEASE_TARBALL

[ -f ../scripts/deploy ]  && ../scripts/deploy  || error Deploy failed. Aborting...
[ -f ../scripts/restart ] && ../scripts/restart || error Restart failed. Aborting...